baseURL: https://ogmc.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Cogito, Ergo Sum
    title: The Journey of Mason Chen 
  blog: {}
  contact:
    address:
      - city: London    
        country: United Kingdom
        street: Happy Street
        title: 888
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: info.masonchen@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (888) 000-6666 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
     # - icon: #--
        label: #--
        url: #--
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/masonchen668
    #  - icon: #--
        label: #--
        url: #--
      - icon: fa-github
        label: GitHub
        url: https://github.com/OGMasonC
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/junchen8/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: #--
        url: #--
      - name: #--
        url: #--
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Biography
        title: About me
        url: blogs/ogmc
      - image: stock.jpg
        subtitle: Risk Return of DJIA Industrial Average
        title: Stock Risk Return Analysis
        url: blogs/risk_return
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: Mason_Chen.jpg
        subtitle: CV
        title: CV
        url: blogs/ogmc
    #  - image: #--
        subtitle: #--
        title: #--
        url: #--
    #  - image: #--
        subtitle: #--
        title: #--
        url: #--
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "The resonable man adapts himself to the world, the unreasonable 
      one persists in trying to adapt the world to himself. Therefore all progess
      depens on the unreasonable man.
      -George Bernard Shaw"
    title: Thank you 
    url: blogs
